src/AppBundle/Entity/ClientStatus.php
<?php
/**
 * Created by PhpStorm.
 * User: muszkin
 * Date: 28.04.17
 * Time: 11:59
 */

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * Class ClientStatus
 * @package AppBundle\Entity
 * @ORM\Entity
 * @ORM\Table(name="client_status")
 */
class ClientStatus
{
    /**
     * @ORM\Id
     * @ORM\Column(name="client_status_id",type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $client_status_id;

    /**
     * @ORM\Column(name="ic_client_id",type="string",nullable=true)
     */
    private $ic_client_id;

    /**
     * @ORM\Column(name="license_id",type="integer")
     */
    private $license_id;

    /**
     * @ORM\Column(name="email_status",type="boolean")
     */
    private $email_status;

    /**
     * @return mixed
     */
    public function getClientStatusId()
    {
        return $this->client_status_id;
    }

    /**
     * @return mixed
     */
    public function getIcClientId()
    {
        return $this->ic_client_id;
    }

    /**
     * @param mixed $ic_client_id
     */
    public function setIcClientId($ic_client_id)
    {
        $this->ic_client_id = $ic_client_id;
    }

    /**
     * @return mixed
     */
    public function getLicenseId()
    {
        return $this->license_id;
    }

    /**
     * @param mixed $license_id
     */
    public function setLicenseId($license_id)
    {
        $this->license_id = $license_id;
    }

    /**
     * @return boolean
     */
    public function getEmailStatus()
    {
        return $this->email_status;
    }

    /**
     * @param mixed $email_status
     */
    public function setEmailStatus($email_status)
    {
        $this->email_status = $email_status;
    }

    /**
     * @return boolean
     */
    public function isEmailSended(){
        return $this->email_status;
    }


}

src/AppBundle/Resources/views/panel/call.list.html.twig
{% block call_list %}
        <div id="call-list" class="panel panel-red">
            <div class="panel-heading">
                <i class="fa fa-list-ul fa-fw"></i> Call list for {{ app.user.fullname }} (total:{{ call_list|length }})
                <div id="curdate"><i class="fa fa-chevron-left fa-fw"></i><span class="text-center">{{ curDate }}</span><i class="fa fa-chevron-right fa-fw"></i></div>
            </div>
            <div class="panel-body">
                <div class="list-group">
                    {% for call in call_list %}
                        <div data-client_id="{{ call.licenseId }}" data-user_email="{{ call.email }}">
                            <a href="#" class="list-group-item">
                                <i class="fa fa-user fa-fw"></i>{% if call.name is null %}{{ call.email }}{% else %}{{ call.name }}{% endif %}{% if call.timeMatters == 1 %} - {{ call.nextDate|date('Y-m-d') }} {{ call.nextTime|date("H:i") }}{% endif %}
                            </a>
                        </div>
                    {% endfor %}
                 </div>
            </div>
        </div>
{% endblock %}

src/AppBundle/Resources/views/panel/client.data.html.twig
{% block client_data %}
    <div class="panel-heading">
        <i class="fa fa-user fa-fw"></i> Client data
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-8">
                <p><i id="client-name" class="fa fa-user fa-fw"></i><a target="_blank" href="{{ crm_link }}">{{ client.name }}</a></p>
                <p><i id="client-email"class="fa fa-envelope-o fa-fw"></i>{{ client.email }}</p>
                <p><i id="client-phone" class="fa fa-phone fa-fw"></i>
                    {% if client.phone is empty %}
                        <a href="#" id="send-email">Send email</a>
                    {% else %}
                        {{ client.phone }} <a href="#" id="makeCall" data-phone="{{ client.phone }}" class="btn btn-xs btn-success">Call</a>
                    {% endif %}
                </p>
            </div>
            <div class="col-lg-4">
                <p><i class="fa fa-wechat fa-fw"></i><a href="https://app.intercom.com/a/apps/{{ app_id }}/users/{{ client.id }}/all-conversations" target="_blank">Intercom Link</a></p>
                <p><i class="fa fa-gears fa-fw"></i><a href="{{ crm_link }}" target="_blank">WHMCS Link</a></p>
                <p><i class="fa fa-ticket fa-fw"></i><a href="{{ support_link }}" target="_blank">Support Tickets</a></p>
            </div>
        </div>
    </div>
    <!-- /.panel-body -->
{% endblock %}

src/AppBundle/Resources/views/panel/client.lisenses.html.twig
{% block client_licenses %}
    {% for license in licenses %}
        <tr data-license="{{ license.license_id.int }}" data-domain="{{ license.domain }}" data-crm-client-id="{{ license.crm_client_id }}" data-crm-license-id="{{ license.crm_license_id }}" class="{% if license.domain is empty %}disable{% endif %}">
            <td>{{ license.license_id.int }}</td>
            <td>{{ license.domain }}</td>
            <td>{{ license.type }}</td>
            <td>{{ license.signed_up }}</td>
            <td>{{ license.status }}</td>
            <td>{% if license.domain is not empty %}{{ license.prospect_status }}{% endif %}</td>
            <td>{% if license.domain is not empty %}{{ license.staff }}{% endif %}</td>
        </tr>
    {% endfor %}
{% endblock client_licenses %}

src/AppBundle/Resources/views/panel/last.concierge.data.html.twig
{% block last_concierge_data %}
    {% if concierge.persona is empty
    and concierge.amount_of_goods is empty
    and concierge.when_to_start is empty
    and concierge.industry is empty
    and concierge.how_much_time_spend is empty
    and concierge.what_to_wait is empty %}
        <p style="text-align: center">No data</p>
    {% else %}
        <p><i class="fa fa-user fa-fw"></i> Persona | <strong id="persona">{{ concierge.persona }}</strong></p>
        <p><i class="fa fa-ticket fa-fw"></i> Amount of goods | <strong id="amount">{{ concierge.amount_of_goods }}</strong></p>
        <p><i class="fa fa-calendar fa-fw"></i> When to start | <strong id="whentostart">{{ concierge.when_to_start }}</strong></p>
        <p><i class="fa fa-suitcase fa-fw"></i> Industry | <strong id="industry">{{ concierge.industry }}</strong></p>
        <p><i class="fa fa-clock-o fa-fw"></i> How much time spend | <strong id="howmuchtime">{{ concierge.how_much_time_spend }}</strong></p>
        <p><i class="fa fa-thumbs-up fa-fw"></i> What to wait | <strong id="whattowait">{{ concierge.what_to_wait }}</strong></p>
    {% endif %}
{% endblock last_concierge_data %}

src/AppBundle/Resources/views/panel/no.concierge.list.html.twig
{% block no_concierge %}

    <div class="panel panel-success">
        <div class="panel-heading">
            <i class="fa fa-play-circle fa-fw"></i> New trial without concierge (based on IC) (total: {{ licenses|length }})
            <a href="#" id="refresh-no-concierge-list-soft" class="btn btn-info">Refresh list</a>
            <a href="#" id="refresh-no-concierge-list-hard" class="btn btn-danger">Refresh list with clearing cache</a>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Sign-Up Date</th>
                        <th>License ID</th>
                        <th>Type</th>
                        <th>Name</th>
                        <th>Email</th>
                    </tr>
                    </thead>
                    <tbody class="body-scrollable" id="no-concierge">
                    {% for list in licenses %}
                        <tr data-client_id="{{ list.0.license_id }}" data-user_email="{{ list.0.email }}" class="list-group-concierge">
                            <td>{{ list.0.created_at }}</td>
                            <td>{{ list.0.license_id }}</td>
                            <td>{{ list.0.type }}</td>
                            <td>{{ list.0.name }}</td>
                            <td>{{ list.0.email }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /.panel-body -->
    </div>


{% endblock no_concierge %}

src/AppBundle/Resources/views/panel/notes.concierge.html.twig
{% block concierge_notes %}
    {% for note in notes %}
        {% if note.note is not empty %}
            <tr>
                <td>{{ note.date }}</td>
                <td>{{ note.staff }}</td>
                <td>{{ note.note }}</td>
            </tr>
        {% endif %}
    {% endfor %}
{% endblock %}

src/AppBundle/Resources/views/panel/sidebar.html.twig
{% block menu %}
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                {#<li class="sidebar-search">#}
                    {#<div class="input-group custom-search-form">#}
                        {#<input type="text" class="form-control" placeholder="Search...">#}
                        {#<span class="input-group-btn">#}
                                {#<button class="btn btn-default" type="button">#}
                                    {#<i class="fa fa-search"></i>#}
                                {#</button>#}
                            {#</span>#}
                    {#</div>#}
                    {#<!-- /input-group -->#}
                {#</li>#}
                <li>
                    <a href="/"><i class="fa fa-dashboard fa-fw"></i> Concierge</a>
                </li>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
{% endblock menu %}

src/AppBundle/Resources/views/panel/statuses.html.twig
{% block statuses %}
    {% for status in statuses %}
        {% if status.status is not empty %}
            <span data-toggle="tooltip" data-placement="bottom" title="" data-original-title="{{ status.date }} | {{ status.staff }}" class="{{ status.status | lower }}" style="{{ percent }}">{{ status.status }}</span>
        {% endif %}
    {% endfor %}
{% endblock %}